name: Build Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  trigger-api-build:
    if: success()
    runs-on: ubuntu-latest
    
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GITHUBAPIKEY }}
        repository: retailcoder/RubberduckAPI
        event-type: new-website-build
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
